default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: myuser
  password: mypass
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: flatiron_mod3_development


test:
  <<: *default
  database: flatiron_mod3_test


production:
  <<: *default
  database: flatiron_mod3_production
