default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("DB_HOST") { "localhost" } %>
  username: myuser
  password: mypass
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: flatiron_mod3_development
  #username: mysite
  #password:
  #host: localhost
  #port: 5432


test:
  <<: *default
  database: flatiron_mod3_test


production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: flatiron_mod3_production
