default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000


development:
  <<: *default
  database: flatiron_mod3_development


test:
  <<: *default
  database: flatiron_mod3_test


production:
  <<: *default
  database: flatiron_mod3_production

