name: Test

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ 'develop', 'release', 'main', '*' ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: docker-compose run -e RAILS_ENV=test --rm blog bundle exec rspec
  code-analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Rubocop check
        run: docker-compose run --rm blog bundle exec rubocop
